name = "tauri-update-cloudflare-1"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-03-26"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
